name: Update Financial History Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 0:00 UTC
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas boto3 python-dotenv matplotlib

      - name: Update history
        run: python crawler/update_history.py

      - name: Fill missing values
        run: python cleaner/fill.py

      - name: Visualize data
        run: python visualize/visualize.py

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: python store_data/upload_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw/history.csv
          git commit -m "Auto-update history.csv [skip ci]" || echo "No changes to commit"
          git push